# Generated by Django 4.2.7 on 2023-11-06 14:43

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(null=True, upload_to=main_app.models.content_file_name),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
