# Generated by Django 4.2.7 on 2023-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employee_gender_employee_profile_employee_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(choices=[('Manchester United', 'Manchester United'), ('Arsenal', 'Arsenal'), ('Chelsea', 'Chelsea'), ('Newcastle', 'Newcastle')], max_length=20, null=True),
        ),
    ]
