# Generated by Django 4.2.7 on 2023-11-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_employee_team_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='teams',
            field=models.CharField(choices=[('Manchester United', 'Manchester United'), ('Arsenal', 'Arsenal'), ('Chelsea', 'Chelsea'), ('Newcastle', 'Newcastle')], default='Arsenal', max_length=100),
        ),
    ]
